name: Test install script

on: [ push, pull_request ]

jobs:
  test_script_linux:
    name: Test install script on Linux ${{ matrix.os }}, ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: centos
            version: latest
          - os: centos
            version: 8
          - os: centos
            version: 7

          - os: opensuse
            version: latest
          - os: opensuse
            version: 15

          - os: ubuntu
            version: latest
          - os: ubuntu
            version: jammy
          - os: ubuntu
            version: focal
          - os: ubuntu
            version: noble

          - os: debian
            version: latest
          - os: debian
            version: buster

          - os: alpine
            version: latest
          - os: alpine
            version: edge
          - os: alpine
            version: 3

          - os: fedora
            version: latest
          - os: fedora
            version: 41
          - os: fedora
            version: 40
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ steps.qemu.outputs.platforms }}

      - name: Pull without cache
        run: docker pull ghcr.io/stephane-segning/bats-docker:${{ matrix.os }}-${{ matrix.version }}

      - name: Test script
        run: |
          docker run --rm -v "$PWD:/app" ghcr.io/stephane-segning/bats-docker:${{ matrix.os }}-${{ matrix.version }} bats /app/scripts/tests/test-script.bats
